use crate::cli::InitArgs;
use crate::exit::{EXIT_GENERAL, ExitError};
use crate::git;
use crate::ops::config;
use crate::ops::lock;
use crate::ops::run;
use crate::pathing::resolve_user_path;
use serde::Serialize;
use std::fs;
use std::io::{self, Write};
use std::path::{Path, PathBuf};
use zip::ZipWriter;
use zip::write::FileOptions;

const DEFAULT_PROJECT_KIT_TEMPLATE: &str = include_str!(concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/docs/PROJECT_KIT_TEMPLATE.md"
));
const DEFAULT_AI_GUIDE_TEMPLATE: &str = include_str!(concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/docs/AI_PROJECT_TEMPLATE.md"
));

#[derive(Debug, Serialize)]
struct InitSummary {
    created_at: String,
    force: bool,
    wrote: Vec<String>,
    skipped: Vec<String>,
    zip_bundle: Option<String>,
}

#[derive(Debug, Clone)]
struct GeneratedMetadata {
    branch: String,
    head: Option<String>,
    forbid_patterns: Vec<String>,
}

#[derive(Debug, Serialize)]
struct RulesZipMetadata {
    generated_at: String,
    run_id: String,
    branch: String,
    head: Option<String>,
    forbid_patterns: Vec<String>,
}

pub fn cmd(git_root: &Path, args: InitArgs) -> Result<(), ExitError> {
    let created_at = lock::now_rfc3339();
    if args.out.is_some() && !args.zip {
        return Err(ExitError::new(EXIT_GENERAL, "--out requires --zip"));
    }

    let lock_path = lock::default_lock_path(git_root);
    let cli_args = build_cli_args(
        args.force,
        args.template_dir.as_deref(),
        args.zip,
        args.out.as_deref(),
    );
    let info = lock::make_lock_info(git_root, "init", &cli_args);
    let _guard = lock::LockGuard::acquire(&lock_path, info)?;

    // Always ensure .diffship exists (repo already ships it, but init should be safe everywhere).
    let diffship_dir = git_root.join(".diffship");
    fs::create_dir_all(&diffship_dir)
        .map_err(|e| ExitError::new(EXIT_GENERAL, format!("failed to create .diffship/: {e}")))?;

    // Create a run directory (M0 spine).
    let run_meta = run::create_run(git_root, "init", &cli_args, created_at.clone())?;
    let run_dir = run::run_dir(git_root, &run_meta.run_id);
    let cwd = std::env::current_dir()
        .map_err(|e| ExitError::new(EXIT_GENERAL, format!("failed to detect current dir: {e}")))?;
    let template_dir = args
        .template_dir
        .as_deref()
        .map(|raw| resolve_user_path(&cwd, raw))
        .transpose()?;
    let zip_out = args
        .out
        .as_deref()
        .map(|raw| resolve_user_path(&cwd, raw))
        .transpose()?;

    let mut wrote = vec![];
    let mut skipped = vec![];
    let metadata = collect_generated_metadata(git_root)?;
    let metadata_block = metadata.markdown_block();

    // 1) Project kit guide (derived from template)
    let kit_out = diffship_dir.join("PROJECT_KIT.md");
    let kit_src = load_template_text(
        template_dir.as_deref(),
        git_root.join("docs").join("PROJECT_KIT_TEMPLATE.md"),
        "PROJECT_KIT_TEMPLATE.md",
        DEFAULT_PROJECT_KIT_TEMPLATE,
    )?;

    let kit_body = format!(
        "# DiffshipOS Project Kit\n\n> Generated by `diffship init`\n\n{}\n{}",
        kit_src, metadata_block
    );

    write_if_needed(&kit_out, &kit_body, args.force, &mut wrote, &mut skipped)?;

    // 2) AI-targeted guide (derived from template)
    let ai_out = diffship_dir.join("AI_GUIDE.md");
    let ai_src = load_template_text(
        template_dir.as_deref(),
        git_root.join("docs").join("AI_PROJECT_TEMPLATE.md"),
        "AI_PROJECT_TEMPLATE.md",
        DEFAULT_AI_GUIDE_TEMPLATE,
    )?;
    let ai_body = format!(
        "# DiffshipOS AI Guide\n\n> Generated by `diffship init`\n\n{}\n{}",
        ai_src, metadata_block
    );
    write_if_needed(&ai_out, &ai_body, args.force, &mut wrote, &mut skipped)?;

    // 3) Diffship-local gitignore for generated state
    let gitignore_out = diffship_dir.join(".gitignore");
    let gitignore_body = default_gitignore();
    write_if_needed(
        &gitignore_out,
        &gitignore_body,
        args.force,
        &mut wrote,
        &mut skipped,
    )?;

    // 4) Config stub
    let cfg_out = diffship_dir.join("config.toml");
    let cfg_body = default_config_stub();
    write_if_needed(&cfg_out, &cfg_body, args.force, &mut wrote, &mut skipped)?;

    let zip_bundle = if args.zip {
        Some(write_rules_zip(
            &diffship_dir,
            &run_meta.run_id,
            &created_at,
            &metadata,
            zip_out.as_deref(),
        )?)
    } else {
        None
    };

    // Write init summary under the run dir
    let summary = InitSummary {
        created_at,
        force: args.force,
        wrote: wrote.clone(),
        skipped: skipped.clone(),
        zip_bundle: zip_bundle.as_ref().map(|path| path.display().to_string()),
    };

    let bytes = serde_json::to_vec_pretty(&summary)
        .map_err(|e| ExitError::new(EXIT_GENERAL, format!("failed to encode init summary: {e}")))?;
    fs::write(run_dir.join("init.json"), bytes)
        .map_err(|e| ExitError::new(EXIT_GENERAL, format!("failed to write init.json: {e}")))?;

    // Human output
    println!("diffship init: ok");
    println!("  git_root : {}", git_root.display());
    println!("  run_id   : {}", run_meta.run_id);
    for p in &wrote {
        println!("  wrote    : {}", p);
    }
    for p in &skipped {
        println!("  skipped  : {}", p);
    }
    if let Some(path) = &zip_bundle {
        println!("  zip      : {}", path.display());
    }

    Ok(())
}

fn load_template_text(
    template_dir: Option<&Path>,
    repo_default: PathBuf,
    file_name: &str,
    built_in: &str,
) -> Result<String, ExitError> {
    if let Some(dir) = template_dir {
        let path = dir.join(file_name);
        if path.is_file() {
            return fs::read_to_string(&path).map_err(|e| {
                ExitError::new(
                    EXIT_GENERAL,
                    format!("failed to read template {}: {e}", path.display()),
                )
            });
        }
    }

    match fs::read_to_string(&repo_default) {
        Ok(s) => Ok(s),
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => Ok(built_in.to_string()),
        Err(e) => Err(ExitError::new(
            EXIT_GENERAL,
            format!("failed to read template {}: {e}", repo_default.display()),
        )),
    }
}

fn build_cli_args(
    force: bool,
    template_dir: Option<&str>,
    zip: bool,
    out: Option<&str>,
) -> Vec<String> {
    let mut v = vec![];
    if force {
        v.push("--force".to_string());
    }
    if let Some(path) = template_dir {
        v.push(format!("--template-dir={path}"));
    }
    if zip {
        v.push("--zip".to_string());
    }
    if let Some(path) = out {
        v.push(format!("--out={path}"));
    }
    v
}

fn collect_generated_metadata(git_root: &Path) -> Result<GeneratedMetadata, ExitError> {
    let head = git::run_git(git_root, ["rev-parse", "HEAD"])
        .ok()
        .map(|s| s.trim().to_string())
        .filter(|s| !s.is_empty());
    let branch = git::run_git(git_root, ["symbolic-ref", "--quiet", "--short", "HEAD"])
        .ok()
        .map(|s| s.trim().to_string())
        .filter(|s| !s.is_empty())
        .unwrap_or_else(|| "(detached)".to_string());
    let forbid_patterns =
        config::resolve_ops_config(git_root, None, Default::default())?.forbid_patterns();
    Ok(GeneratedMetadata {
        branch,
        head,
        forbid_patterns,
    })
}

fn write_if_needed(
    path: &std::path::Path,
    body: &str,
    force: bool,
    wrote: &mut Vec<String>,
    skipped: &mut Vec<String>,
) -> Result<(), ExitError> {
    if path.exists() && !force {
        skipped.push(path.display().to_string());
        return Ok(());
    }

    fs::write(path, body).map_err(|e| {
        ExitError::new(
            EXIT_GENERAL,
            format!("failed to write {}: {e}", path.display()),
        )
    })?;
    wrote.push(path.display().to_string());
    Ok(())
}

fn default_config_stub() -> String {
    // Keep it minimal and future-proof; precedence rules are implemented in M4.
    // This file is intended to be committed if the user wants stable project defaults.
    r#"# diffship project configuration (generated by `diffship init`)
#
# See also: docs/CONFIG.md
# Precedence: CLI > manifest > project > global > default
#
# Use this file in two layers:
# - Keep the core defaults aligned with how this repository actually uses diffship
# - Edit the "Customize this section" blocks with repo-specific defaults and local-only commands

# Customize this section: choose default verify behavior for this repository.
# Use a built-in profile (`fast`, `standard`, `full`) or define `[verify.profiles."<name>"]` below.

[verify]
default_profile = "standard" # fast|standard|full

# Customize this section: choose default handoff packing behavior.
# `output_dir` is the parent directory for auto-generated bundle names.
[handoff]
default_profile = "20x512"   # built-in: 20x512|10x100 or a custom [handoff.profiles."<name>"]
output_dir = "./.diffship/artifacts/handoffs" # optional parent dir for auto-generated bundle names

# Customize this section: add named handoff profiles shared by this repository or team.
# Copy `[handoff.profiles.*]` stanzas into another repo or `~/.config/diffship/config.toml`
# if you want to share the same named limits across projects.
# [handoff.profiles."team-ci"]
# max_parts = 8
# max_bytes_per_part = 104857600
#
# `plan.toml` exports the selected profile name plus resolved numeric limits.
# It does not export the full profile catalog.

# Customize this section: choose how successful verified runs are promoted.
[ops.promote]
mode = "commit"           # none|working-tree|commit
target_branch = "develop"

# Customize this section: decide whether diffship commits automatically after verify succeeds.
[ops.commit]
policy = "auto"            # auto|manual

# Customize this section: local-only commands to run automatically after a successful apply.
# These are local-only config values; patch bundles cannot define them.
# [ops.post_apply]
# cmd1 = "just fmt-fix"
# cmd2 = "just docs-check"
# cmd3 = "just trace-check"
# cmd4 = "just ci"

# Customize this section: forbid AI patch bundles from touching fragile files in this repository.
# Values are repo-relative path or glob patterns matched during apply/loop validation.
# [ops.forbid]
# path1 = "pnpm-lock.yaml"
# path2 = "package-lock.json"

# ---
# Planned / reserved keys (kept here for future versions):
#
# [ops]
# run_dir = ".diffship/runs"
# lock_path = ".diffship/lock"
# require_clean_tree = true
# require_base_commit_match = true
"#
    .to_string()
}

fn default_gitignore() -> String {
    r#"artifacts/handoffs/
artifacts/rules/
runs/
worktrees/
sessions/
lock
"#
    .to_string()
}

impl GeneratedMetadata {
    fn markdown_block(&self) -> String {
        let mut out = String::new();
        out.push_str("\n## Generated metadata\n\n");
        out.push_str(&format!("- Current branch: `{}`\n", self.branch));
        match self.head.as_deref() {
            Some(head) => out.push_str(&format!("- Repository HEAD: `{}`\n", head)),
            None => out.push_str("- Repository HEAD: (unavailable)\n"),
        }
        if self.forbid_patterns.is_empty() {
            out.push_str("- Active `[ops.forbid]` patterns: (none)\n");
        } else {
            out.push_str("- Active `[ops.forbid]` patterns:\n");
            for pattern in &self.forbid_patterns {
                out.push_str(&format!("  - `{}`\n", pattern));
            }
        }
        out
    }
}

fn write_rules_zip(
    diffship_dir: &Path,
    run_id: &str,
    created_at: &str,
    metadata: &GeneratedMetadata,
    out: Option<&Path>,
) -> Result<PathBuf, ExitError> {
    let out_path = match out {
        Some(path) => path.to_path_buf(),
        None => default_rules_zip_path(diffship_dir, metadata.head.as_deref(), run_id),
    };
    if let Some(parent) = out_path.parent() {
        fs::create_dir_all(parent).map_err(|e| {
            ExitError::new(
                EXIT_GENERAL,
                format!("failed to create zip output dir {}: {e}", parent.display()),
            )
        })?;
    }

    let file = fs::File::create(&out_path)
        .map_err(|e| ExitError::new(EXIT_GENERAL, format!("failed to create zip: {e}")))?;
    let mut zip = ZipWriter::new(file);
    let opts = FileOptions::default()
        .compression_method(zip::CompressionMethod::Deflated)
        .unix_permissions(0o644);

    add_file_to_zip(
        &mut zip,
        opts,
        &diffship_dir.join("PROJECT_KIT.md"),
        "PROJECT_KIT.md",
    )?;
    add_file_to_zip(
        &mut zip,
        opts,
        &diffship_dir.join("AI_GUIDE.md"),
        "AI_GUIDE.md",
    )?;

    let metadata_json = serde_json::to_vec_pretty(&RulesZipMetadata {
        generated_at: created_at.to_string(),
        run_id: run_id.to_string(),
        branch: metadata.branch.clone(),
        head: metadata.head.clone(),
        forbid_patterns: metadata.forbid_patterns.clone(),
    })
    .map_err(|e| {
        ExitError::new(
            EXIT_GENERAL,
            format!("failed to encode rules zip metadata: {e}"),
        )
    })?;
    add_bytes_to_zip(&mut zip, opts, "metadata.json", &metadata_json)?;

    zip.finish()
        .map_err(|e| ExitError::new(EXIT_GENERAL, format!("failed to finalize zip: {e}")))?;
    Ok(out_path)
}

fn default_rules_zip_path(diffship_dir: &Path, head: Option<&str>, run_id: &str) -> PathBuf {
    let stem = head
        .map(|value| value.chars().take(12).collect::<String>())
        .filter(|value| !value.is_empty())
        .unwrap_or_else(|| run_id.to_string());
    diffship_dir
        .join("artifacts")
        .join("rules")
        .join(format!("rules_{stem}.zip"))
}

fn add_file_to_zip<W: Write + io::Seek>(
    zip: &mut ZipWriter<W>,
    opts: FileOptions,
    src: &Path,
    dst: &str,
) -> Result<(), ExitError> {
    let bytes = fs::read(src).map_err(|e| {
        ExitError::new(
            EXIT_GENERAL,
            format!("failed to read {}: {e}", src.display()),
        )
    })?;
    add_bytes_to_zip(zip, opts, dst, &bytes)
}

fn add_bytes_to_zip<W: Write + io::Seek>(
    zip: &mut ZipWriter<W>,
    opts: FileOptions,
    path: &str,
    bytes: &[u8],
) -> Result<(), ExitError> {
    zip.start_file(path, opts)
        .map_err(|e| ExitError::new(EXIT_GENERAL, format!("zip start_file failed: {e}")))?;
    zip.write_all(bytes)
        .map_err(|e| ExitError::new(EXIT_GENERAL, format!("zip write failed: {e}")))?;
    Ok(())
}
