use crate::cli::InitArgs;
use crate::exit::{EXIT_GENERAL, ExitError};
use crate::ops::lock;
use crate::ops::run;
use serde::Serialize;
use std::fs;
use std::path::Path;

const DEFAULT_PROJECT_KIT_TEMPLATE: &str = include_str!(concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/docs/PROJECT_KIT_TEMPLATE.md"
));
const DEFAULT_AI_GUIDE_TEMPLATE: &str = include_str!(concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/docs/AI_PROJECT_TEMPLATE.md"
));

#[derive(Debug, Serialize)]
struct InitSummary {
    created_at: String,
    force: bool,
    wrote: Vec<String>,
    skipped: Vec<String>,
}

pub fn cmd(git_root: &Path, args: InitArgs) -> Result<(), ExitError> {
    let created_at = lock::now_rfc3339();

    let lock_path = lock::default_lock_path(git_root);
    let cli_args = build_cli_args(args.force);
    let info = lock::make_lock_info(git_root, "init", &cli_args);
    let _guard = lock::LockGuard::acquire(&lock_path, info)?;

    // Always ensure .diffship exists (repo already ships it, but init should be safe everywhere).
    let diffship_dir = git_root.join(".diffship");
    fs::create_dir_all(&diffship_dir)
        .map_err(|e| ExitError::new(EXIT_GENERAL, format!("failed to create .diffship/: {e}")))?;

    // Create a run directory (M0 spine).
    let run_meta = run::create_run(git_root, "init", &cli_args, created_at.clone())?;
    let run_dir = run::run_dir(git_root, &run_meta.run_id);

    let mut wrote = vec![];
    let mut skipped = vec![];

    // 1) Project kit guide (derived from template)
    let kit_out = diffship_dir.join("PROJECT_KIT.md");
    let kit_template = git_root.join("docs").join("PROJECT_KIT_TEMPLATE.md");

    let kit_src = match fs::read_to_string(&kit_template) {
        Ok(s) => s,
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => {
            DEFAULT_PROJECT_KIT_TEMPLATE.to_string()
        }
        Err(e) => {
            return Err(ExitError::new(
                EXIT_GENERAL,
                format!("failed to read template {}: {e}", kit_template.display()),
            ));
        }
    };

    let kit_body = format!(
        "# DiffshipOS Project Kit\n\n> Generated by `diffship init`\n\n{}",
        kit_src
    );

    write_if_needed(&kit_out, &kit_body, args.force, &mut wrote, &mut skipped)?;

    // 2) AI-targeted guide (derived from template)
    let ai_out = diffship_dir.join("AI_GUIDE.md");
    let ai_template = git_root.join("docs").join("AI_PROJECT_TEMPLATE.md");
    let ai_src = match fs::read_to_string(&ai_template) {
        Ok(s) => s,
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => DEFAULT_AI_GUIDE_TEMPLATE.to_string(),
        Err(e) => {
            return Err(ExitError::new(
                EXIT_GENERAL,
                format!("failed to read template {}: {e}", ai_template.display()),
            ));
        }
    };
    let ai_body = format!(
        "# DiffshipOS AI Guide\n\n> Generated by `diffship init`\n\n{}",
        ai_src
    );
    write_if_needed(&ai_out, &ai_body, args.force, &mut wrote, &mut skipped)?;

    // 3) Config stub
    let cfg_out = diffship_dir.join("config.toml");
    let cfg_body = default_config_stub();
    write_if_needed(&cfg_out, &cfg_body, args.force, &mut wrote, &mut skipped)?;

    // Write init summary under the run dir
    let summary = InitSummary {
        created_at,
        force: args.force,
        wrote: wrote.clone(),
        skipped: skipped.clone(),
    };

    let bytes = serde_json::to_vec_pretty(&summary)
        .map_err(|e| ExitError::new(EXIT_GENERAL, format!("failed to encode init summary: {e}")))?;
    fs::write(run_dir.join("init.json"), bytes)
        .map_err(|e| ExitError::new(EXIT_GENERAL, format!("failed to write init.json: {e}")))?;

    // Human output
    println!("diffship init: ok");
    println!("  git_root : {}", git_root.display());
    println!("  run_id   : {}", run_meta.run_id);
    for p in &wrote {
        println!("  wrote    : {}", p);
    }
    for p in &skipped {
        println!("  skipped  : {}", p);
    }

    Ok(())
}

fn build_cli_args(force: bool) -> Vec<String> {
    let mut v = vec![];
    if force {
        v.push("--force".to_string());
    }
    v
}

fn write_if_needed(
    path: &std::path::Path,
    body: &str,
    force: bool,
    wrote: &mut Vec<String>,
    skipped: &mut Vec<String>,
) -> Result<(), ExitError> {
    if path.exists() && !force {
        skipped.push(path.display().to_string());
        return Ok(());
    }

    fs::write(path, body).map_err(|e| {
        ExitError::new(
            EXIT_GENERAL,
            format!("failed to write {}: {e}", path.display()),
        )
    })?;
    wrote.push(path.display().to_string());
    Ok(())
}

fn default_config_stub() -> String {
    // Keep it minimal and future-proof; precedence rules are implemented in M4.
    // This file is intended to be committed if the user wants stable project defaults.
    r#"# diffship project configuration (generated by `diffship init`)
#
# See also: docs/CONFIG.md
# Precedence: CLI > manifest > project > global > default

[verify]
default_profile = "standard" # fast|standard|full

[handoff]
default_profile = "20x512"   # built-in: 20x512|10x100 or a custom [handoff.profiles."<name>"]
# output_dir = "./artifacts/handoffs" # optional parent dir for auto-generated bundle names

# Example custom handoff profile:
# Copy `[handoff.profiles.*]` stanzas into another repo or `~/.config/diffship/config.toml`
# if you want to share the same named limits across projects.
# [handoff.profiles."team-ci"]
# max_parts = 8
# max_bytes_per_part = 104857600
#
# `plan.toml` exports the selected profile name plus resolved numeric limits.
# It does not export the full profile catalog.

[ops.promote]
mode = "commit"           # none|working-tree|commit
target_branch = "develop"

[ops.commit]
policy = "auto"            # auto|manual

# Optional commands to run automatically in the sandbox after a successful apply.
# These are local-only config values; patch bundles cannot define them.
# [ops.post_apply]
# cmd1 = "just fmt-fix"
# cmd2 = "just docs-check"
# cmd3 = "just trace-check"
# cmd4 = "just ci"

# ---
# Planned / reserved keys (kept here for future versions):
#
# [ops]
# run_dir = ".diffship/runs"
# lock_path = ".diffship/lock"
# require_clean_tree = true
# require_base_commit_match = true
"#
    .to_string()
}
